[state]
name = "mainnet"
display_name = "Ethereum Mainnet"
union = "ethereum"
chain_id = "1"
is_default = true

[endpoints]
rpc_url = "https://eth.llamarpc.com"
explorer_url = "https://etherscan.io"

[currency]
symbol = "ETH"
